name: Package and publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]
    environment: pypi
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Poetry
        run: pipx install poetry --python $(which python)

      - name: Install project
        run: poetry install

      - name: Test with tox
        run: poetry run tox

      - name: Build package
        run: poetry build

      - name: Publish package
        env:
            PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: poetry publish -u __token__ -p "$PYPI_API_TOKEN"
