name: Test, lint, and build library

on: [push, pull_request]

jobs:
  test-library:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Poetry
        run: pipx install poetry --python $(which python)

      - name: Install project
        run: poetry install

      - name: Test with tox
        run: poetry run tox

  test-deps:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.11, 3.12, 3.13]

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Poetry
        run: pipx install poetry --python $(which python)

      - name: Check pyproject.toml
        run: poetry check

      - name: Check if lockfile is updated
        run: poetry lock --check
