name: Test, lint, and build library

on: [push, pull_request]

jobs:
  test-library:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python 3.13
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry --python $(which python)

      - name: Install project
        run: poetry install

      - name: Test with tox
        run: poetry run tox

  test-deps:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.13"

      - name: Install Poetry
        run: pipx install poetry --python $(which python)

      - name: Check pyproject.toml
        run: poetry check

      - name: Check if lockfile is updated
        run: poetry lock --check
